url: https://bhigy.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
title: Bertrand Higy
email: bertrand.higy@protonmail.com
description: "My personal page."



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    type: fab
    url: http://github.com/bhigy
  - title: linkedin
    type: fab
    url: http://www.linkedin.com/in/bertrandhigy
  - title: building
    type: fa
    url: https://www.ru.nl/english/people/higy-b/


# Postal address (add as many lines as necessary)
address:
  - line: Radboud University
  - line: Centre for Language and Speech Technology
  - line: Attn. Bertrand Higy - Room 8.15
  - line: Postbus 9103
  - line: 6500 HD NIJMEGEN
  - line: The Netherlands

# Build settings
markdown: kramdown
permalink: pretty
