url: https://bhigy.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
title: Bertrand Higy
email: bertrand.higy@protonmail.com
description: "My personal page."



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    type: fab
    url: http://github.com/bhigy
  - title: linkedin
    type: fab
    url: http://www.linkedin.com/in/bertrandhigy
  - title: building
    type: fa
    url: https://research.tilburguniversity.edu/en/persons/bertrand-higy


# Postal address (add as many lines as necessary)
address:
  - line: Tilburg University
  - line: Attn. Bertrand Higy - Room 138
  - line: PO Box 90153
  - line: 5000 LE Tilburg
  - line: The Netherlands

# Build settings
markdown: kramdown
permalink: pretty
