# Site settings
title: Bertrand Higy
person_name: Bertrand Higy
person_nickname: bhigy
email: #pbagnpg\100wvzru\056zr
mailto: #"&#109;&#97;&#105;&#108;&#116;&#111;&#58;%63%6s%6r%74%61%63%74@%6n%69%6q%65%68.%6q%65"
description: PhD Fellow
baseurl: "" # the subpath of your site, e.g. /blog/
hostname: bhigy.github.io # used to determine if google analytics should be triggered
url: http://bhigy.github.io # the base hostname & protocol for your site
permalink: /:title/

blog_url: #https://jimeh.io/
cv_url: http://bhigy.github.io/files/bertrand_higy_cv.pdf
vcard_url: #http://assets.jimeh.me/jim-myhrberg.vcf
twitter_username: #jimeh
github_username: bhigy
linkedin_username: bertrandhigy
facebook_username: #jimeh
flickr_username: #jimeh
lastfm_username: #jimeh

# Build settings
markdown: kramdown
