url: https://bhigy.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
title: Bertrand Higy
email: bertrand.higy@gmail.com
description: "My personal page."



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    type: fab
    url: http://github.com/bhigy
  - title: linkedin
    type: fab
    url: http://www.linkedin.com/in/bertrandhigy
  - title: building
    type: fa
    url: https://www.iit.it/people/bertrand-higy


# Postal address (add as many lines as necessary)
address:
  - line: iCub Facility
  - line: Istituto Italiano di Tecnologia
  - line: Via Morego, 30
  - line: Genova 16163, Italy

# Build settings
markdown: kramdown
permalink: pretty
